-- AlterTable
ALTER TABLE "PushCampaign" 
ADD COLUMN IF NOT EXISTS "frequency" TEXT DEFAULT 'ONCE',
ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "targetingType" TEXT DEFAULT 'ALL',
ADD COLUMN IF NOT EXISTS "targetCustomerIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "tagId" TEXT,
ADD COLUMN IF NOT EXISTS "message" TEXT,
ADD COLUMN IF NOT EXISTS "nextRunAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "lastRunAt" TIMESTAMP(3);
