-- demoRobot dev seed: RobotModel + 3 model-specific Flows + 1 generic
-- fallback Flow + 2 sample Assets, for the DemoRobotica workspace.
--
-- Fixture/test data only — NOT a real-customer-data import mechanism
-- (analisi.md §12.1). compiledPrompt/retrievalDocument/hash below were
-- generated by the real compileFlow() (apps/backend/src/application/demorobot/
-- flow-compiler.service.ts), not hand-written, so they match the actual
-- compiler contract byte-for-byte.
--
-- Guarded on the workspace slug so it only runs against the intended
-- DemoRobotica workspace and is idempotent (ON CONFLICT DO NOTHING).

DO $$
DECLARE
  v_workspace_id TEXT;
BEGIN
  SELECT id INTO v_workspace_id FROM "Workspace" WHERE slug = 'demorobotica' LIMIT 1;

  IF v_workspace_id IS NULL THEN
    RAISE NOTICE 'DemoRobotica workspace not found (slug=demorobotica) — skipping demoRobot seed.';
    RETURN;
  END IF;

  -- Align workspace configuration with the demoRobot custom chatbot module
  -- (analisi.md §2, §12.1) — was created from a generic e-commerce template.
  UPDATE "Workspace"
  SET "customChatbotId" = 'demorobot',
      "businessType" = 'other',
      "welcomeMessage" = 'Welcome! I''m your DemoRobot technical support assistant. I can help you diagnose problems with your robot. How can I help you today?',
      "hasProductCatalog" = false,
      "hasCart" = false,
      "hasOrderTracking" = false
  WHERE id = v_workspace_id;

  -- RobotModel
  INSERT INTO "robot_models" (id, "workspaceId", name, slug, manufacturer, description, "lookupRules", "createdAt", "updatedAt")
  VALUES ('cm_seed_demorobot_x200', v_workspace_id, 'RoboCut X200', 'robocut-x200', 'DemoRobotica', 'Robot da giardinaggio/taglio erba, modello di test per lo sviluppo.', '{"prefix": "RCX200"}'::jsonb, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO "demorobot_flows" (id, "workspaceId", "robotModelId", title, description, keywords, "retrievalDocument", embedding, "compiledPrompt", hash, "createdAt", "updatedAt")
  VALUES ('cm_seed_flow_rumore', v_workspace_id, 'cm_seed_demorobot_x200', 'Rumore strano', 'Diagnostica per rumori anomali durante il funzionamento — copre il pattern a check sequenziali fino a escalation finale.', ARRAY['vibra', 'cigola', 'ronzio']::TEXT[], 'Rumore strano
vibra, cigola, ronzio
Il robot è acceso?
Il wifi è connesso?
Il cut scheduling è attivo?
Tutti i check sono OK ma il rumore persiste. Serve un tecnico.', ARRAY[]::DOUBLE PRECISION[], '## FLOW: Rumore strano

### Q: Il robot è acceso?
- If "Sì" → continue to: "Il wifi è connesso?"

### Q: Il wifi è connesso?
(collect as: wifiConnected, type: boolean)
- If "Sì" → continue to: "Il cut scheduling è attivo?"

### Q: Il cut scheduling è attivo?
(collect as: cutSchedulingActive, type: boolean)
- If "Sì" → continue to: "Tutti i check sono OK ma il rumore persiste. Serve un tecnico."

### Q: Tutti i check sono OK ma il rumore persiste. Serve un tecnico.
(terminal: ESCALATE, allowed tools: remember, escalate_to_operator)
', 'f8dacc4f04aecd709eed7b477b91ea565beaf3185d1a1d5c9151c58fef006b7b', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO "demorobot_flows" (id, "workspaceId", "robotModelId", title, description, keywords, "retrievalDocument", embedding, "compiledPrompt", hash, "createdAt", "updatedAt")
  VALUES ('cm_seed_flow_wifi', v_workspace_id, 'cm_seed_demorobot_x200', 'Wifi non si connette', 'Diagnostica connettività wifi — copre il pattern puramente self-service.', ARRAY['wifi', 'rete', 'connessione']::TEXT[], 'Wifi non si connette
wifi, rete, connessione
Il led wifi lampeggia?
Prova a riavviare il router e il robot. Il problema è risolto?', ARRAY[]::DOUBLE PRECISION[], '## FLOW: Wifi non si connette

### Q: Il led wifi lampeggia?
(collect as: wifiLedBlinking, type: boolean)
- If "Sì" → continue to: "Prova a riavviare il router e il robot. Il problema è risolto?"

### Q: Prova a riavviare il router e il robot. Il problema è risolto?
(terminal: SELF_SERVICE, allowed tools: remember)
', '5ef21cd8e14b79aa7a29132b4b7b90960c93e72c5bb980d51c2ea9d4aba9fa34', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO "demorobot_flows" (id, "workspaceId", "robotModelId", title, description, keywords, "retrievalDocument", embedding, "compiledPrompt", hash, "createdAt", "updatedAt")
  VALUES ('cm_seed_flow_fumo', v_workspace_id, 'cm_seed_demorobot_x200', 'Il robot fa fumo', 'Caso di emergenza tecnica — copre il pattern di escalation immediata su una singola risposta a metà percorso.', ARRAY['fumo', 'bruciato', 'odore']::TEXT[], 'Il robot fa fumo
fumo, bruciato, odore
Il robot sta ancora fumando in questo momento?
Verifica visivamente eventuali danni esterni. Il problema è risolto?', ARRAY[]::DOUBLE PRECISION[], '## FLOW: Il robot fa fumo

### Q: Il robot sta ancora fumando in questo momento?
- If "Sì" → call escalate_to_operator immediately.
- If "No" → continue to: "Verifica visivamente eventuali danni esterni. Il problema è risolto?"

### Q: Verifica visivamente eventuali danni esterni. Il problema è risolto?
(terminal: SELF_SERVICE, allowed tools: remember)
', 'd577d8e3f9a22a169d3aaf3fa08f89ab819102dd9265df8c421dc22551a6aa03', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO "demorobot_flows" (id, "workspaceId", "robotModelId", title, description, keywords, "retrievalDocument", embedding, "compiledPrompt", hash, "createdAt", "updatedAt")
  VALUES ('cm_seed_flow_generic', v_workspace_id, NULL, 'Diagnostica generica', 'Flow di fallback del workspace, usato quando il retrieval non trova un match specifico per il modello.', ARRAY[]::TEXT[], 'Diagnostica generica
Il robot è acceso?
Il wifi è connesso?
Il cut scheduling è attivo?
Tutti i check base sono OK. Serve un tecnico per una diagnosi più approfondita.', ARRAY[]::DOUBLE PRECISION[], '## FLOW: Diagnostica generica

### Q: Il robot è acceso?
- If "Sì" → continue to: "Il wifi è connesso?"

### Q: Il wifi è connesso?
(collect as: wifiConnected, type: boolean)
- If "Sì" → continue to: "Il cut scheduling è attivo?"

### Q: Il cut scheduling è attivo?
(collect as: cutSchedulingActive, type: boolean)
- If "Sì" → continue to: "Tutti i check base sono OK. Serve un tecnico per una diagnosi più approfondita."

### Q: Tutti i check base sono OK. Serve un tecnico per una diagnosi più approfondita.
(terminal: ESCALATE, allowed tools: remember, escalate_to_operator)
', '0716f3e497b474f0cc7c748adaed098758ca174f407ad0c68ce3fd37c662cabd', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
  ON CONFLICT (id) DO NOTHING;

  -- FlowNode + FlowEdge for flow1 (Rumore strano)
  INSERT INTO "demorobot_flow_nodes" (id, "flowId", question, "positionX", "positionY", "fieldKey", "fieldType", "terminalType", "createdAt", "updatedAt") VALUES
    ('rs_n1', 'cm_seed_flow_rumore', 'Il robot è acceso?', 0, 0, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rs_n2', 'cm_seed_flow_rumore', 'Il wifi è connesso?', 280, 0, 'wifiConnected', 'boolean', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rs_n3', 'cm_seed_flow_rumore', 'Il cut scheduling è attivo?', 560, 0, 'cutSchedulingActive', 'boolean', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('rs_n4', 'cm_seed_flow_rumore', 'Tutti i check sono OK ma il rumore persiste. Serve un tecnico.', 840, 0, NULL, NULL, 'ESCALATE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO "demorobot_flow_edges" (id, "sourceNodeId", "targetNodeId", label, "triggersEscalation", "createdAt") VALUES
    ('rs_e1', 'rs_n1', 'rs_n2', 'Sì', false, CURRENT_TIMESTAMP),
    ('rs_e2', 'rs_n2', 'rs_n3', 'Sì', false, CURRENT_TIMESTAMP),
    ('rs_e3', 'rs_n3', 'rs_n4', 'Sì', false, CURRENT_TIMESTAMP)
  ON CONFLICT (id) DO NOTHING;

  -- FlowNode + FlowEdge for flow2 (Wifi non si connette)
  INSERT INTO "demorobot_flow_nodes" (id, "flowId", question, "positionX", "positionY", "fieldKey", "fieldType", "terminalType", "createdAt", "updatedAt") VALUES
    ('wf_n1', 'cm_seed_flow_wifi', 'Il led wifi lampeggia?', 0, 0, 'wifiLedBlinking', 'boolean', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('wf_n2', 'cm_seed_flow_wifi', 'Prova a riavviare il router e il robot. Il problema è risolto?', 280, 0, NULL, NULL, 'SELF_SERVICE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO "demorobot_flow_edges" (id, "sourceNodeId", "targetNodeId", label, "triggersEscalation", "createdAt") VALUES
    ('wf_e1', 'wf_n1', 'wf_n2', 'Sì', false, CURRENT_TIMESTAMP)
  ON CONFLICT (id) DO NOTHING;

  -- FlowNode + FlowEdge for flow3 (Il robot fa fumo) — immediate escalation on one answer
  INSERT INTO "demorobot_flow_nodes" (id, "flowId", question, "positionX", "positionY", "fieldKey", "fieldType", "terminalType", "createdAt", "updatedAt") VALUES
    ('sm_n1', 'cm_seed_flow_fumo', 'Il robot sta ancora fumando in questo momento?', 0, 0, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('sm_n2', 'cm_seed_flow_fumo', 'Verifica visivamente eventuali danni esterni. Il problema è risolto?', 280, 120, NULL, NULL, 'SELF_SERVICE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO "demorobot_flow_edges" (id, "sourceNodeId", "targetNodeId", label, "triggersEscalation", "createdAt") VALUES
    ('sm_e1', 'sm_n1', NULL, 'Sì', true, CURRENT_TIMESTAMP),
    ('sm_e2', 'sm_n1', 'sm_n2', 'No', false, CURRENT_TIMESTAMP)
  ON CONFLICT (id) DO NOTHING;

  -- FlowNode + FlowEdge for the generic fallback flow
  INSERT INTO "demorobot_flow_nodes" (id, "flowId", question, "positionX", "positionY", "fieldKey", "fieldType", "terminalType", "createdAt", "updatedAt") VALUES
    ('gn_n1', 'cm_seed_flow_generic', 'Il robot è acceso?', 0, 0, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('gn_n2', 'cm_seed_flow_generic', 'Il wifi è connesso?', 280, 0, 'wifiConnected', 'boolean', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('gn_n3', 'cm_seed_flow_generic', 'Il cut scheduling è attivo?', 560, 0, 'cutSchedulingActive', 'boolean', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('gn_n4', 'cm_seed_flow_generic', 'Tutti i check base sono OK. Serve un tecnico per una diagnosi più approfondita.', 840, 0, NULL, NULL, 'ESCALATE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO "demorobot_flow_edges" (id, "sourceNodeId", "targetNodeId", label, "triggersEscalation", "createdAt") VALUES
    ('gn_e1', 'gn_n1', 'gn_n2', 'Sì', false, CURRENT_TIMESTAMP),
    ('gn_e2', 'gn_n2', 'gn_n3', 'Sì', false, CURRENT_TIMESTAMP),
    ('gn_e3', 'gn_n3', 'gn_n4', 'Sì', false, CURRENT_TIMESTAMP)
  ON CONFLICT (id) DO NOTHING;

  -- Sample assets (analisi.md §12.1: 1 PDF finto + 1 immagine, per verificare
  -- §8 — consegna al cliente, mai knowledge base). Placeholder URLs: these
  -- are dev fixtures, not real uploaded files.
  INSERT INTO "demorobot_assets" (id, "robotModelId", type, url, title, summary, language, "createdAt", "updatedAt") VALUES
    ('cm_seed_asset_manual', 'cm_seed_demorobot_x200', 'document', 'https://example.com/demorobot/manuale-x200.pdf', 'Manuale RoboCut X200', 'Manuale utente completo del robot, incluse istruzioni per il reset wifi.', 'it', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('cm_seed_asset_photo', 'cm_seed_demorobot_x200', 'image', 'https://example.com/demorobot/led-wifi-x200.jpg', 'Foto del led wifi', 'Foto di riferimento per individuare il led wifi sul robot.', 'it', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
  ON CONFLICT (id) DO NOTHING;

END $$;
