/**
 * Test Suite: ContactOperator Email Notifications
 */

const mockEmailService = {
  sendOperatorNotificationEmail: jest.fn().mockResolvedValue(true),
}

const mockSummaryAgent = {
  generateSummary: jest.fn().mockResolvedValue({
    success: true,
    summary: "Cliente ha richiesto assistenza per prodotto scaduto ricevuto.",
  }),
}

const mockSafetyAgent = {
  process: jest.fn().mockResolvedValue({
    translatedText: "Cliente ha richiesto assistenza per prodotto scaduto ricevuto.",
    safe: true,
  }),
}

jest.mock("../../../src/application/services/email.service", () => ({
  EmailService: jest.fn().mockImplementation(() => mockEmailService),
}))

jest.mock("../../../src/services/summary-agent-llm.service", () => ({
  SummaryAgentLLM: jest.fn().mockImplementation(() => mockSummaryAgent),
}))

jest.mock("../../../src/application/agents/SafetyTranslationAgent", () => ({
  SafetyTranslationAgent: jest.fn().mockImplementation(() => mockSafetyAgent),
}))

jest.mock("../../../src/utils/logger", () => ({
  __esModule: true,
  default: {
    info: jest.fn(),
    warn: jest.fn(),
    error: jest.fn(),
    debug: jest.fn(),
  },
}))

const mockPrisma = {
  customers: {
    findFirst: jest.fn(),
    update: jest.fn(),
  },
  chatSession: {
    findFirst: jest.fn(),
  },
  conversationMessage: {
    findMany: jest.fn(),
  },
  whatsAppQueue: {
    create: jest.fn(),
  },
  workspace: {
    findUnique: jest.fn(),
  },
  user: {
    findFirst: jest.fn(),
  },
  $disconnect: jest.fn(),
}

jest.mock("@echatbot/database", () => ({
  prisma: mockPrisma,
}))

import { contactOperator, ContactOperatorRequest } from "../../../src/domain/calling-functions/contactOperator"
import { EmailService } from "../../../src/application/services/email.service"
import logger from "../../../src/utils/logger"

describe("ContactOperator Email Notifications", () => {
  const workspaceId = "ws-test-123"
  const customerId = "cust-test-123"
  const phoneNumber = "+393331234567"
  const sessionId = "session-123"

  const mockSalesAgent = {
    id: "sales-123",
    firstName: "Giovanni",
    lastName: "Bianchi",
    email: "giovanni.bianchi@bellitalia.com",
    phone: "+393339876543",
  }

  const mockCustomer = {
    id: customerId,
    name: "Mario Rossi",
    email: "mario@example.com",
    phone: phoneNumber,
    workspaceId,
    salesId: mockSalesAgent.id,
    sales: mockSalesAgent,
    activeChatbot: true,
  }

  const mockWorkspace = {
    id: workspaceId,
    name: "BellItalia Foods",
    operatorContactMethod: "email", // 🆕 Test email method
    operatorEmail: "support@bellitalia.com",
    operatorWhatsappNumber: null,
    hasHumanSupport: true,
    hasSalesAgents: true, // ✅ Enable sales agent routing
    whatsappSettings: {
      adminEmail: "admin@bellitalia.com",
    },
  }

  const mockMessages = [
    {
      id: "msg-1",
      role: "user",
      content: "Ho ricevuto merce scaduta!",
      createdAt: new Date(),
    },
    {
      id: "msg-2",
      role: "assistant",
      content: "Mi dispiace molto per l'inconveniente. Ci può dire quale prodotto?",
      createdAt: new Date(),
    },
    {
      id: "msg-3",
      role: "user",
      content: "Il parmigiano era scaduto da una settimana!",
      createdAt: new Date(),
    },
  ]

  beforeEach(() => {
    jest.clearAllMocks()

    mockPrisma.customers.findFirst.mockResolvedValue(mockCustomer)
    mockPrisma.customers.update.mockResolvedValue(mockCustomer)
    mockPrisma.chatSession.findFirst.mockResolvedValue({
      id: sessionId,
      customerId,
      status: "active",
    })
    mockPrisma.conversationMessage.findMany.mockResolvedValue(mockMessages)
    mockPrisma.workspace.findUnique.mockResolvedValue(mockWorkspace)
    mockEmailService.sendOperatorNotificationEmail.mockResolvedValue(true)
    mockSummaryAgent.generateSummary.mockResolvedValue({
      success: true,
      summary: "Cliente Mario Rossi ha richiesto assistenza per prodotto scaduto.",
    })
    mockSafetyAgent.process.mockResolvedValue({
      translatedText: "Cliente Mario Rossi ha richiesto assistenza per prodotto scaduto.",
      safe: true,
    })
  })

  describe("Email sent to sales agent", () => {
    it("should send email to assigned agent when available", async () => {
      // ✅ New rule: if agent is assigned, email goes to agent
      const request: ContactOperatorRequest = {
        phoneNumber,
        workspaceId,
        customerId,
        reason: "Prodotto scaduto",
      }

      await contactOperator(request)

      expect(mockEmailService.sendOperatorNotificationEmail).toHaveBeenCalledTimes(1)
      expect(mockEmailService.sendOperatorNotificationEmail).toHaveBeenCalledWith(
        expect.objectContaining({
          to: "giovanni.bianchi@bellitalia.com", // 🎯 agent email
        })
      )
    })

    it("should include AI-generated chat summary in the email (not empty)", async () => {
      // SCENARIO: Email notification must contain the chat summary generated by SummaryAgentLLM
      // RULE: The chatSummary passed to sendOperatorNotificationEmail must NOT be empty.
      //   This verifies the scoping fix: chatSummary is assigned in the outer scope
      //   so both email (inside if(session)) and WhatsApp (outside if(session)) get the value.
      const request: ContactOperatorRequest = {
        phoneNumber,
        workspaceId,
        customerId,
        reason: "Prodotto scaduto",
      }

      await contactOperator(request)

      expect(mockEmailService.sendOperatorNotificationEmail).toHaveBeenCalledTimes(1)
      const emailCallArgs = mockEmailService.sendOperatorNotificationEmail.mock.calls[0][0]
      
      // chatSummary must contain the generated summary text, NOT be empty ""
      expect(emailCallArgs.chatSummary).toBeDefined()
      expect(emailCallArgs.chatSummary.length).toBeGreaterThan(50)
      expect(emailCallArgs.chatSummary).toContain("Mario Rossi")
      expect(emailCallArgs.chatSummary).toContain(phoneNumber)
      // Should contain the AI-generated summary content
      expect(emailCallArgs.chatSummary).toContain("assistenza per prodotto scaduto")
    })
  })

  describe("Priority Logic - Email targets", () => {
    it("should fallback to workspace.operatorEmail when agent email is missing", async () => {
      const mockCustomerNoAgentEmail = {
        ...mockCustomer,
        sales: { ...mockSalesAgent, email: "" },
      }
      mockPrisma.customers.findFirst.mockResolvedValue(mockCustomerNoAgentEmail)
      
      const request: ContactOperatorRequest = {
        phoneNumber,
        workspaceId,
        customerId,
        reason: "Expired product",
      }

      await contactOperator(request)

      expect(mockEmailService.sendOperatorNotificationEmail).toHaveBeenCalledTimes(1)
      expect(mockEmailService.sendOperatorNotificationEmail).toHaveBeenCalledWith(
        expect.objectContaining({
          to: "support@bellitalia.com", // 🎯 workspace.operatorEmail
          customerName: mockCustomer.name,
        })
      )
    })

    it("should fallback to adminEmail when agent email and operatorEmail are null", async () => {
      const mockCustomerNoAgentEmail = {
        ...mockCustomer,
        sales: { ...mockSalesAgent, email: "" },
      }
      mockPrisma.customers.findFirst.mockResolvedValue(mockCustomerNoAgentEmail)
      
      const mockWorkspaceNoOperatorEmail = {
        ...mockWorkspace,
        operatorEmail: null,
      }

      mockPrisma.workspace.findUnique.mockResolvedValue(mockWorkspaceNoOperatorEmail)

      const request: ContactOperatorRequest = {
        phoneNumber,
        workspaceId,
        customerId,
        reason: "Need help",
      }

      await contactOperator(request)
      
      expect(mockEmailService.sendOperatorNotificationEmail).toHaveBeenCalledTimes(1)
      expect(mockEmailService.sendOperatorNotificationEmail).toHaveBeenCalledWith(
        expect.objectContaining({
          to: "admin@bellitalia.com", // 🎯 Fallback to whatsappSettings.adminEmail
          customerName: mockCustomer.name,
        })
      )
    })

    it("should NOT send email when agent email, operatorEmail, and adminEmail are null", async () => {
      // SCENARIO: No email configured anywhere
      
      const mockCustomerNoAgentEmail = {
        ...mockCustomer,
        sales: { ...mockSalesAgent, email: "" },
      }
      mockPrisma.customers.findFirst.mockResolvedValue(mockCustomerNoAgentEmail)

      const mockWorkspaceNoEmails = {
        ...mockWorkspace,
        operatorEmail: null,
        whatsappSettings: {
          adminEmail: null,
        },
      }

      mockPrisma.workspace.findUnique.mockResolvedValue(mockWorkspaceNoEmails)

      const request: ContactOperatorRequest = {
        phoneNumber,
        workspaceId,
        customerId,
      }

      await contactOperator(request)
      
      // ❌ No email sent (no target)
      expect(mockEmailService.sendOperatorNotificationEmail).not.toHaveBeenCalled()
    })
  })

  describe("Contact method selection", () => {
    it("should NOT send email when operatorContactMethod is whatsapp", async () => {
      const mockWorkspaceWhatsApp = {
        ...mockWorkspace,
        operatorContactMethod: "whatsapp",
      }
      mockPrisma.workspace.findUnique.mockResolvedValue(mockWorkspaceWhatsApp)

      const request: ContactOperatorRequest = {
        phoneNumber,
        workspaceId,
        customerId,
      }

      await contactOperator(request)

      expect(mockEmailService.sendOperatorNotificationEmail).not.toHaveBeenCalled()
    })
  })

  describe("WhatsApp notification routing", () => {
    it("should send WhatsApp to assigned agent when available", async () => {
      const mockWorkspaceWhatsApp = {
        ...mockWorkspace,
        operatorContactMethod: "whatsapp",
        operatorWhatsappNumber: "+393330000000",
      }
      mockPrisma.workspace.findUnique.mockResolvedValue(mockWorkspaceWhatsApp)

      const request: ContactOperatorRequest = {
        phoneNumber,
        workspaceId,
        customerId,
      }

      await contactOperator(request)

      expect(mockPrisma.whatsAppQueue.create).toHaveBeenCalledTimes(1)
      expect(mockPrisma.whatsAppQueue.create).toHaveBeenCalledWith(
        expect.objectContaining({
          data: expect.objectContaining({
            phoneNumber: mockSalesAgent.phone, // 🎯 agent phone
          }),
        })
      )
    })
  })

  describe("WorkspaceId filter in ContactOperator", () => {
    it("should filter customer by phone AND workspaceId", async () => {
      const request: ContactOperatorRequest = {
        phoneNumber,
        workspaceId,
        customerId,
      }

      await contactOperator(request)

      expect(mockPrisma.customers.findFirst).toHaveBeenCalledWith(
        expect.objectContaining({
          where: {
            phone: phoneNumber,
            workspaceId,
          },
        })
      )
    })
  })
})
