/**
 * Setup 2FA Page
 * Displayed after registration to configure TOTP 2FA
 * 
 * FLOW:
 * 1. Display QR code from registration response
 * 2. User scans with Google Authenticator
 * 3. User enters 6-digit code to verify
 * 4. Redirect to workspace selection
 * 
 * NOTE: Recovery codes are generated by backend but not shown to user
 * DESIGN: Aligned with RegisterPage (shadcn/ui + Card)
 */

import { useState, useEffect } from 'react'
import { useNavigate, useLocation, Link } from 'react-router-dom'
import QRCode from 'react-qr-code'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { LanguageSelector } from '@/components/shared/LanguageSelector'
import { toast } from '@/lib/toast'
import { logger } from '@/lib/logger'
import { Loader2, CheckCircle, AlertCircle, Smartphone, Copy, Download } from 'lucide-react'
import { api } from '@/services/api'

export default function Setup2FAPage() {
  const navigate = useNavigate()
  const location = useLocation()
  
  // Get state from registration
  const { userId, email, firstName, qrCode, provider } = location.state || {}
  
  // Page state
  const [step, setStep] = useState<'scan' | 'verify' | 'codes'>('scan')
  const [loading, setLoading] = useState(false)
  const [verificationCode, setVerificationCode] = useState('')
  const [error, setError] = useState('')
  const [recoveryCodes, setRecoveryCodes] = useState<string[]>([])
  const [codesCopied, setCodesCopied] = useState(false)

  /**
   * Redirect if no state provided
   */
  useEffect(() => {
    console.log('🔍 Setup2FA - Received qrCode:', qrCode)
    console.log('🔍 QR Code length:', qrCode?.length)
    console.log('🔍 QR Code starts with:', qrCode?.substring(0, 50))
    
    if (!userId || !qrCode) {
      toast.error('Invalid setup link. Please register again.')
      navigate('/auth/register')
    }
  }, [userId, qrCode, navigate])

  /**
   * Verify TOTP code and get recovery codes
   */
  const handleVerify = async () => {
    if (!verificationCode || verificationCode.length !== 6) {
      setError('Please enter a valid 6-digit code')
      return
    }

    setLoading(true)
    setError('')
    
    try {
      const response = await api.post('/auth/verify-2fa-setup', {
        userId,
        code: verificationCode,
      })
      
      const { recoveryCodes: codes, token, user } = response.data
      
      // Save token for authentication (JWT-only)
      logger.info('🔐 [Setup2FA] verify-2fa-setup response:', { token, user })
      
      if (!token) {
        logger.error('❌ [Setup2FA] CRITICAL: Backend did not return token!')
        toast.error('Authentication failed - no token received')
        return
      }
      
      // 🛡️ CRITICAL SECURITY: Clear ALL storage before saving new credentials
      logger.info('🧹 [Setup2FA] Clearing ALL storage (localStorage + sessionStorage)')
      
      // 🔍 DEBUG: Log OLD token before clearing
      const oldToken = localStorage.getItem('token')
      logger.warn(`🔍 [Setup2FA] OLD token in storage: ${oldToken?.substring(0, 30)}...`)
      
      localStorage.clear()
      sessionStorage.clear()
      logger.info('✅ [Setup2FA] Storage cleared completely')
      
      // 🔍 DEBUG: Verify storage is actually empty
      const checkToken = localStorage.getItem('token')
      if (checkToken) {
        logger.error('❌ [Setup2FA] CRITICAL: localStorage.clear() FAILED - token still exists!')
        alert('CRITICAL BUG: localStorage not clearing! Check console.')
        return
      }
      logger.info('✅ [Setup2FA] Verified: storage is empty')
      
      logger.info(`🔍 [Setup2FA] NEW token to be saved: ${token.substring(0, 30)}...`)
      
      // Decode and log NEW token details
      const newTokenDecoded = JSON.parse(atob(token.split('.')[1]))
      logger.warn(`🔍 [Setup2FA] NEW token decoded:`, newTokenDecoded)
      logger.warn(`   Email in new token: ${newTokenDecoded.email}`)
      logger.warn(`   User ID in new token: ${newTokenDecoded.id}`)
      
      // Save new authentication data (ONLY token - no sessionId)
      localStorage.setItem('token', token)
      
      // 🔥 ALERT for debugging - REMOVE after testing
      alert(`✅ NEW TOKEN SAVED!\nEmail: ${newTokenDecoded.email}\nID: ${newTokenDecoded.id}`)
      
      // Verify immediately that the token was saved correctly
      const savedToken = localStorage.getItem('token')
      if (savedToken !== token) {
        logger.error('❌ [Setup2FA] Token mismatch after save!')
        logger.error(`Expected: ${token.substring(0, 30)}...`)
        logger.error(`Got: ${savedToken?.substring(0, 30)}...`)
        toast.error('Token save failed')
        return
      }
      
      if (user) {
        localStorage.setItem('user', JSON.stringify(user))
      }
      
      // Verify token saved correctly
      const verifyToken = localStorage.getItem('token')
      
      logger.info(`✅ [Setup2FA] Token saved: ${verifyToken ? verifyToken.substring(0, 20) + '...' : 'NULL'}`)
      
      if (!verifyToken) {
        logger.error('❌ [Setup2FA] CRITICAL: Token save failed!')
        toast.error('Authentication storage failed')
        return
      }
      
      // Show recovery codes
      if (codes && codes.length > 0) {
        setRecoveryCodes(codes)
        setStep('codes')
        toast.success('2FA enabled successfully! Please save your recovery codes.')
      } else {
        // No recovery codes - go directly to workspace
        toast.success('2FA enabled successfully!')
        setTimeout(() => {
          navigate('/workspace-selection')
        }, 200)
      }
    } catch (error: any) {
      const errorMessage = error.response?.data?.message || 'Codice di verifica non valido'
      setError(errorMessage)
      toast.error(errorMessage)
    } finally {
      setLoading(false)
    }
  }

  /**
   * Copy recovery codes to clipboard
   */
  const handleCopyRecoveryCodes = () => {
    const codesText = recoveryCodes.join('\n')
    navigator.clipboard.writeText(codesText)
    setCodesCopied(true)
    toast.success('Recovery codes copied to clipboard!')
    setTimeout(() => setCodesCopied(false), 3000)
  }

  /**
   * Download recovery codes as text file
   */
  const handleDownloadRecoveryCodes = () => {
    const codesText = recoveryCodes.join('\n')
    const blob = new Blob([`ShopME Recovery Codes\n\nEmail: ${email}\nGenerated: ${new Date().toLocaleString()}\n\n${codesText}\n\nKeep these codes in a safe place. Each code can only be used once.`], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `shopme-recovery-codes-${email}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success('Recovery codes downloaded!')
  }

  /**
   * Continue to workspace after saving codes
   */
  const handleContinueToWorkspace = () => {
    // 🔒 SECURITY: Verify we have token before navigating
    const currentToken = localStorage.getItem('token')
    
    logger.info('🔍 [Setup2FA] Verifying authentication before navigation:', {
      hasToken: !!currentToken,
      tokenPreview: currentToken ? currentToken.substring(0, 30) + '...' : 'NULL',
    })
    
    if (!currentToken) {
      logger.error('❌ [Setup2FA] Missing token at navigation time!')
      toast.error('Authentication error. Please login again.')
      navigate('/auth/login')
      return
    }
    
    toast.success('Setup complete! Redirecting...')
    
    // 🛡️ CRITICAL SECURITY FIX: DON'T reload old token!
    // The token is ALREADY in localStorage from step 1 (line 109)
    // Just verify it exists and navigate
    logger.info('🔍 [Setup2FA COMPLETE] Verifying token exists in storage')
    
    const existingToken = localStorage.getItem('token')
    if (!existingToken) {
      logger.error('❌ [Setup2FA COMPLETE] No token in storage!')
      toast.error('Authentication failed - please try again')
      navigate('/auth/login')
      return
    }
    
    logger.info(`✅ [Setup2FA COMPLETE] Token verified: ${existingToken.substring(0, 30)}...`)
    
    // CRITICAL: Log token details for debugging
    logger.warn(`🔍 [Setup2FA COMPLETE] Token in localStorage:`)
    logger.warn(`   Full token: ${existingToken}`)
    logger.warn(`   Decoded (manual): ${JSON.stringify(parseJwt(existingToken))}`)
    
    // Navigate to workspace selection
    logger.info('🔄 [Setup2FA] Navigating to /workspace-selection')
    navigate('/workspace-selection')
  }

  // Helper to decode JWT (for debugging)
  const parseJwt = (token: string) => {
    try {
      return JSON.parse(atob(token.split('.')[1]))
    } catch (e) {
      return null
    }
  }

  /**
   * Render QR code scan step
   */
  const renderScanStep = () => (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle className="text-2xl flex items-center gap-2">
          <Smartphone className="w-6 h-6 text-green-600" />
          Setup Two-Factor Authentication
        </CardTitle>
        <CardDescription>
          Scan the QR code with your authenticator app
        </CardDescription>
      </CardHeader>
      
      <CardContent className="space-y-6">
        {/* QR Code Display */}
        <div className="flex flex-col items-center space-y-4">
          <div className="bg-white p-4 rounded-lg border-2 border-gray-200">
            <QRCode value={qrCode} size={200} />
          </div>
          
          <Alert>
            <AlertCircle className="h-4 w-4" />
            <AlertTitle>Use an authenticator app</AlertTitle>
            <AlertDescription>
              Recommended: <strong>Google Authenticator</strong>, Microsoft Authenticator, or Authy
            </AlertDescription>
          </Alert>
        </div>

        {/* Instructions */}
        <div className="space-y-3 text-sm text-gray-600">
          <p className="font-semibold text-gray-900">How to setup:</p>
          <ol className="list-decimal list-inside space-y-2">
            <li>Open your authenticator app</li>
            <li>Tap "+" or "Add account"</li>
            <li>Scan this QR code</li>
            <li>Enter the 6-digit code below</li>
          </ol>
        </div>
      </CardContent>
      
      <CardFooter>
        <Button 
          onClick={() => setStep('verify')} 
          className="w-full bg-green-600 hover:bg-green-700"
        >
          I've scanned the code
        </Button>
      </CardFooter>
    </Card>
  )

  /**
   * Render verification code input step
   */
  const renderVerifyStep = () => (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle className="text-2xl">Verify Your Setup</CardTitle>
        <CardDescription>
          Enter the 6-digit code from your authenticator app
        </CardDescription>
      </CardHeader>
      
      <CardContent className="space-y-4">
        {/* Verification Code Input */}
        <div className="space-y-2">
          <Label htmlFor="verificationCode">Verification Code</Label>
          <Input
            id="verificationCode"
            type="text"
            inputMode="numeric"
            pattern="[0-9]*"
            maxLength={6}
            placeholder="000000"
            value={verificationCode}
            onChange={(e) => {
              const value = e.target.value.replace(/\D/g, '')
              setVerificationCode(value)
              setError('')
            }}
            onKeyDown={(e) => e.key === 'Enter' && handleVerify()}
            className="text-center text-2xl tracking-widest font-mono"
            disabled={loading}
          />
          {error && (
            <p className="text-sm text-red-600">{error}</p>
          )}
        </div>

        <Alert>
          <AlertCircle className="h-4 w-4" />
          <AlertDescription>
            The code refreshes every 30 seconds. Enter the current code from your app.
          </AlertDescription>
        </Alert>
      </CardContent>
      
      <CardFooter className="flex flex-col gap-3">
        <Button 
          onClick={handleVerify}
          disabled={loading || verificationCode.length !== 6}
          className="w-full bg-green-600 hover:bg-green-700"
        >
          {loading ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Verifying...
            </>
          ) : (
            'Verify and Continue'
          )}
        </Button>
        
        <Button 
          variant="outline"
          onClick={() => setStep('scan')}
          disabled={loading}
          className="w-full"
        >
          Back to QR Code
        </Button>
      </CardFooter>
    </Card>
  )

  /**
   * Render recovery codes step
   */
  const renderCodesStep = () => (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle className="text-2xl flex items-center gap-2">
          <CheckCircle className="w-6 h-6 text-green-600" />
          Save Your Recovery Codes
        </CardTitle>
        <CardDescription>
          Store these codes in a safe place. You'll need them to access your account if you lose your authenticator device.
        </CardDescription>
      </CardHeader>
      
      <CardContent className="space-y-4">
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Important!</AlertTitle>
          <AlertDescription>
            Each recovery code can only be used once. After using a code, it will be invalidated.
          </AlertDescription>
        </Alert>

        {/* Recovery Codes Display */}
        <div className="bg-gray-50 rounded-lg p-4 border-2 border-gray-200">
          <div className="grid grid-cols-2 gap-2 font-mono text-sm">
            {recoveryCodes.map((code, index) => (
              <div key={index} className="bg-white px-3 py-2 rounded border border-gray-300 text-center">
                {code}
              </div>
            ))}
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex gap-2">
          <Button
            variant="outline"
            onClick={handleCopyRecoveryCodes}
            className="flex-1"
          >
            <Copy className="mr-2 h-4 w-4" />
            {codesCopied ? 'Copied!' : 'Copy Codes'}
          </Button>
          
          <Button
            variant="outline"
            onClick={handleDownloadRecoveryCodes}
            className="flex-1"
          >
            <Download className="mr-2 h-4 w-4" />
            Download
          </Button>
        </div>
      </CardContent>
      
      <CardFooter>
        <Button 
          onClick={handleContinueToWorkspace}
          className="w-full bg-green-600 hover:bg-green-700"
        >
          I've Saved My Codes - Continue
        </Button>
      </CardFooter>
    </Card>
  )

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 to-blue-50 flex items-center justify-center p-4">
      <div className="absolute top-4 right-4">
        <LanguageSelector />
      </div>
      <div className="w-full max-w-md">
        {/* Step Indicator */}
        <div className="mb-6 flex justify-center items-center gap-2 text-sm text-gray-600">
          <div className={`flex items-center gap-1 ${step === 'scan' ? 'font-semibold text-green-600' : ''}`}>
            <span className={`w-6 h-6 rounded-full flex items-center justify-center border-2 ${step === 'scan' ? 'bg-green-600 text-white border-green-600' : step === 'verify' || step === 'codes' ? 'bg-green-600 text-white border-green-600' : 'border-gray-300'}`}>
              {step === 'verify' || step === 'codes' ? <CheckCircle className="w-4 h-4" /> : '1'}
            </span>
            Scan
          </div>
          
          <div className="w-8 h-0.5 bg-gray-300" />
          
          <div className={`flex items-center gap-1 ${step === 'verify' ? 'font-semibold text-green-600' : ''}`}>
            <span className={`w-6 h-6 rounded-full flex items-center justify-center border-2 ${step === 'verify' ? 'bg-green-600 text-white border-green-600' : step === 'codes' ? 'bg-green-600 text-white border-green-600' : 'border-gray-300'}`}>
              {step === 'codes' ? <CheckCircle className="w-4 h-4" /> : '2'}
            </span>
            Verify
          </div>
          
          <div className="w-8 h-0.5 bg-gray-300" />
          
          <div className={`flex items-center gap-1 ${step === 'codes' ? 'font-semibold text-green-600' : ''}`}>
            <span className={`w-6 h-6 rounded-full flex items-center justify-center border-2 ${step === 'codes' ? 'bg-green-600 text-white border-green-600' : 'border-gray-300'}`}>
              3
            </span>
            Save Codes
          </div>
        </div>

        {/* Main Content */}
        {step === 'scan' && renderScanStep()}
        {step === 'verify' && renderVerifyStep()}
        {step === 'codes' && renderCodesStep()}

        {/* Footer */}
        <div className="mt-6 text-center text-sm text-gray-600">
          <Link to="/auth/login" className="text-green-600 hover:text-green-700 hover:underline">
            Skip and login later
          </Link>
        </div>
      </div>
    </div>
  )
}
