-- Rename channelStatus column to channelStatus
-- Context: "channel" was an error - the correct term is "channel"
-- This column controls whether the chatbot/channel is enabled or disabled
-- NOTE: Column already exists in schema, so this is a no-op migration
-- ALTER TABLE "Workspace" RENAME COLUMN "channelStatus" TO "channelStatus";
