/**
 * Outbound Link Guard
 *
 * Deterministic security layer: removes from OUTBOUND bot messages every URL
 * whose domain is not authorized for the workspace (workspace.allowedExternalLinks
 * merged with the platform-internal domains).
 *
 * Iron rule #16: this is a code guarantee, NOT a prompt rule. The LLM-based
 * SecurityAgent may still run, but even when it fails (parse error, timeout,
 * false negative) no unauthorized link can reach the customer.
 *
 * No replacement text is injected when a URL is removed: hardcoded copy in any
 * language is forbidden (CLAUDE.md rule 1A) — the link is silently dropped and
 * the event is logged for the operator.
 */

import logger from "../../utils/logger"

/**
 * Platform-internal domains, always allowed on every workspace.
 * Mirrors the list used by SecurityAgent's LLM prompt: short links,
 * registration, cart, orders and profile pages are generated by the platform
 * itself and must never be stripped.
 */
export const INTERNAL_ALLOWED_DOMAINS = [
  "echatbot.ai",
  "www.echatbot.ai",
]

const URL_REGEX = /https?:\/\/[^\s<>"'\])]+/gi

/**
 * True when the URL's hostname matches one of the allowed entries.
 *
 * Matching semantics (same as SecurityAgent.isAllowedUrl):
 * - exact hostname match ("stripe.com" allows https://stripe.com/...)
 * - www equivalence ("stripe.com" also allows https://www.stripe.com and
 *   "www.stripe.com" also allows https://stripe.com)
 * - entries containing a path (e.g. "echatbot.ai/s/*") match by prefix on the
 *   URL without protocol and without leading "www.", "*" wildcard stripped
 */
export function isUrlAllowed(url: string, allowedDomains: string[]): boolean {
  let hostname: string
  try {
    hostname = new URL(url).hostname.toLowerCase()
  } catch {
    return false
  }

  const urlWithoutProtocol = url
    .replace(/^https?:\/\//i, "")
    .replace(/^www\./i, "")
    .toLowerCase()

  return allowedDomains.some((domain) => {
    const d = domain.trim().toLowerCase()
    if (!d) return false

    if (d.includes("/")) {
      const prefix = d.replace(/^www\./, "").replace(/\*+$/, "")
      return urlWithoutProtocol.startsWith(prefix)
    }

    return (
      hostname === d ||
      hostname === `www.${d}` ||
      (d.startsWith("www.") && hostname === d.slice(4))
    )
  })
}

/**
 * The URLs in `message` NOT covered by the allow-list (internal domains merged
 * with the workspace's allowedExternalLinks), in order of appearance.
 *
 * The FAIL-CLOSED companion of sanitizeOutboundLinks: chat replies strip the
 * bad link and deliver the rest, but a push-campaign message without its link
 * is broken marketing — those callers block the send (or reject the campaign
 * at creation) when this returns anything.
 */
export function findUnauthorizedUrls(
  message: string,
  workspaceAllowedDomains: string[]
): string[] {
  if (!message) return []
  const allowedDomains = [
    ...INTERNAL_ALLOWED_DOMAINS,
    ...(workspaceAllowedDomains || []),
  ]
  const urls = message.match(URL_REGEX) || []
  return urls.filter((url) => !isUrlAllowed(url, allowedDomains))
}

export interface SanitizeResult {
  message: string
  removedUrls: string[]
}

/**
 * Removes every URL not covered by the allowed domains from an outbound
 * message. Whitespace left behind by a removed URL is collapsed so the
 * remaining sentence stays readable.
 */
export function sanitizeOutboundLinks(
  message: string,
  workspaceAllowedDomains: string[],
  context?: { workspaceId?: string; customerId?: string }
): SanitizeResult {
  if (!message) return { message, removedUrls: [] }

  const allowedDomains = [
    ...INTERNAL_ALLOWED_DOMAINS,
    ...(workspaceAllowedDomains || []),
  ]

  const removedUrls: string[] = []

  const sanitized = message.replace(URL_REGEX, (url) => {
    if (isUrlAllowed(url, allowedDomains)) return url
    removedUrls.push(url)
    return ""
  })

  if (removedUrls.length === 0) {
    return { message, removedUrls }
  }

  logger.warn("🚨 [OUTBOUND-LINK-GUARD] Removed unauthorized link(s) from bot reply", {
    workspaceId: context?.workspaceId,
    customerId: context?.customerId,
    removedUrls,
    allowedDomains,
  })

  const cleaned = sanitized
    .replace(/[ \t]{2,}/g, " ")
    .replace(/ +([.,;:!?])/g, "$1")
    .replace(/^[ \t]+|[ \t]+$/gm, "")

  return { message: cleaned, removedUrls }
}
